apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: fintrack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: fintrack-auth-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/fintrack_auth
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fintrack-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fintrack-secret
                  key: POSTGRES_PASSWORD
            - name: APPLICATION_SECURITY_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fintrack-secret
                  key: JWT_SECRET
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: fintrack-config
                  key: REDIS_HOST
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: fintrack
spec:
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081