apiVersion: v1
kind: Secret
metadata:
  name: fintrack-secret
  namespace: fintrack
type: Opaque
stringData:
  POSTGRES_USER: fintrack_user
  POSTGRES_PASSWORD: fintrack_pass
  JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970